### ISSUE TITLE
can you compile it and add a release

### ISSUE THREAD

**Issue by kyv0n** [LtUnkn0wn2/YoloSpammer#1]
title i always have problems when trying to compile things in visual studio

**Comment by LtUnkn0wn2** [comment]
Go To https://github.com/LtUnkn0wn2/YoloSpammer/tree/master/YoloSpammer/YoloSpammer/bin/Debug
And dowload the .exe and Leaf.xNet.dll

**Comment by kyv0n** [comment]
> Go To https://github.com/LtUnkn0wn2/YoloSpammer/tree/master/YoloSpammer/YoloSpammer/bin/Debug
> And dowload the .exe and Leaf.xNet.dll

Thanks i found it out i just had to download leaf.xnet from the nuget program console

**Comment by LtUnkn0wn2** [comment]
No Problem How You Enjoy 👍 :)
